### PR TITLE
Fix/improve energy deposition for coupled neutron-photon calculations

### PR DESCRIPTION
**Pull request by paulromano**
This pull request makes two important changes:

- In a coupled neutron-photon calculation, tallying `heating-local` right now does not give the correct answer. The problem is that photons end up contributing to this score when they should not. The solution is to just ensure that when heating-local is being scored, only neutrons contribute.
- Also in a coupled n-g calculation, right now OpenMC doesn't account for energy released as delayed photons when you ask for the `heating` score. The photon yield and energy spectrum that is provided in the data files only corresponds to the prompt photons. To account for the energy of delayed photons, what I've done here is to artificially increase the fission photon yields to account for the energy release of delayed photons. If EGP and EGD are the average energies released as prompt and delayed photons, the prompt yields are multiplied by (EGP + EGD)/EGP. This is an approximation because 1) the actual yield of delayed photons depends on the power history (at time 0 there are _no_ delayed photons) and 2) their spectrum is not the same as the prompt spectrum. But, usually it is better to include that energy than not. I have put in a new setting (`Settings.delayed_photon_scaling`) so that this behavior can be turned off if desired.

One other unrelated change is that when messages are displayed to stdout, I've made sure to flush them (via `std::endl`) so that buffering doesn't result in delayed output (this tends to occur if you are running OpenMC from IPython/Jupyter notebook).

## Results

I've done some simple tests looking at energy deposition for a PWR pin cell problem to confirm that the changes here give answers that make sense. For the full results, have a look at [this notebook](https://nbviewer.jupyter.org/gist/paulromano/89c78dc74d98215a8f2a406753b2215d?force_flush=true), but the summary is as follows:

- `'heating` and `heating-local` both give reasonable answers when used to determine the average amount of fission energy deposited per fission (surprise: around 200 MeV)
- In theory, `heating` and `heating-local` _should_ produce the same answer if there is no leakage in the problem, but they don't for a number of reasons:
  1. In the ENDF/B-VII.1 data, there is a mismatch between the energy release data from MT=458 and the prompt fission yield given. [This paper](https://doi.org/10.1016/j.anucene.2019.02.003) discusses it in more detail.
  2. Right now, our thick-target bremsstrahlung treatment does not conserve energy, so we end up producing a little more energy than we should. However, this ends up being a small effect compared with the effect from the data mismatch (in the notebook, I ran the calculations with TTB turned off).

@drewejohnson You're probably most familiar with the motivation for this change; care to review?

### CODE REVIEW

**Comment by drewejohnson** [comment]
It looks good to me, just want to make sure I'm on the same page with your logic. Our `heating-local` tally provides energy production from incident neutrons assuming energy from photons is deposited locally. Having photons then contribute to this tally is then essentially a double count of photon energy production.

We also make this clear in the [Specifying tallies](https://docs.openmc.org/en/latest/usersguide/tallies.html#scores) section that `heating-local` should "only be used for incident neutrons."

**Comment by makeclean** [comment]
Would it not be weird if heating-local only applied to neutrons, if I were in photon transport mode I would expect that to mean If i deposited all my current energy in a collision locally e.g. TTB appoximation off (i think. I think we need to be very careful here, to be honest - Im already a little confused.

**Comment by paulromano** [comment]
@drewejohnson That's exactly right. The description of the `heating-local` score does say that it should only be used for neutrons already. Did you want me to add something about that elsewhere?

@makeclean I understand the potential confusion. This score really is intended for a neutron transport calculation where you want to get energy deposition but you don't want to simulate photons. If we were to have it do what you suggest (tally energy dep without TTB), then in a coupled n-γ simulation photons will get double counted. There is an option to turn TTB off (settings.electron_treatment) -- that will obviously change the physics. The heating-local score doesn't change any physics; it's just using a different heating number (one that assumes photons are deposited locally). Beyond expanding our description of the score to explain this a little more, I'm not sure what an acceptable solution would be. Let me know if you have suggestions.

**Comment by drewejohnson** [comment]
@paulromano Great, just remembering how much fun that energy deposition stuff was... I don't think changes need to be made to the documentation, just wanted to point out that our docs explain when `heating-local` should not be used :+1:

**Pull request merged**
