### PR TITLE
Prepare for NumPy 2.0

### PR DESCRIPTION
**Pull request by paulromano**
# Description

NumPy is going to be making a major release (2.0) soon that is backwards incompatible. Thankfully, there's very little we need to change in OpenMC in order to prepare for the 2.0 release. The only thing that needed to be changed was to replace `np.string_` with `np.bytes_` as mentioned in the [migration guide](https://numpy.org/devdocs/numpy_2_0_migration_guide.html). 

# Checklist

- [x] I have performed a self-review of my own code
- [x] <s>I have run [clang-format](https://docs.openmc.org/en/latest/devguide/styleguide.html#automatic-formatting) (version 15) on any C++ source files (if applicable)</s>
- [x] I have followed the [style guidelines](https://docs.openmc.org/en/latest/devguide/styleguide.html#python) for Python source files (if applicable)
- [x] <s>I have made corresponding changes to the documentation (if applicable)</s>
- [x] <s>I have added tests that prove my fix is effective or that my feature works (if applicable)</s>

### CODE REVIEW

**Review by nelsonag — COMMENTED** [review]
I have reviewed the changes provided and performed greps for all items on the numpy 2 migration guide. 
I only have one comment, which is not necessary for merge as it doesn't affect 2.0 compatibility:
- numpy 2.0.0 deprecates np.trapz which we use twice within our codebase. We should consider moving to scipy.integrate.trapezoid instead.

One observation that does not need to be incorporated, as it doesn't effect numpy 2.0.0 compatibility, is that np.trapz is deprecated

**Comment by paulromano** [comment]
@nelsonag Do you have any further requests on this PR?

**Comment by eepeterson** [comment]
@paulromano this looks good to me so far. I think the small amount of Cython used in the repo should be fine because it was using Cython > 3.0. I did go through the other [Ruff rules for numpy](https://docs.astral.sh/ruff/rules/#numpy-specific-rules-npy) after looking through the migration guide and noticed we are using legacy functions from `numpy.random` in the Python API and it's recommended to update to using `numpy.random.Generator` if we don't need these to be exactly the same. The offending lines can be found with Ruff rule [NPY002](https://docs.astral.sh/ruff/rules/numpy-legacy-random/). Let me know if you want to tackle those here or not. If not I think this is good to go.

**Comment by paulromano** [comment]
@eepeterson Thanks for pointing that out about `numpy.random`. I played around with it a little and can't get it to produce the same random numbers, so I think it's probably best if we handle that as a separate PR. As is, the legacy RNG stuff _does_ still work with numpy 2.0 so it's not an imminent issue.

**Comment by paulromano** [comment]
Actually jk, if I use `numpy.random.RandomState` it does produce the same random numbers. I'll incorporate that in this PR. If we want to change the default RNG used, _that_ we can do as a separate PR.

**Comment by paulromano** [comment]
@eepeterson OK, just took care of the NPY002 warnings from ruff :heavy_check_mark:

**Pull request merged**
