### PR TITLE
added git actions workflow file

### PR DESCRIPTION
**Pull request by Shimwell**
Just a thought but I'm wondering if the recently updated dockerfile could be automatically build and published on dockerhub each time a push to develop branch is made.

There is a Github action for automating such a task https://github.com/docker/build-push-action

This PR would need to be accompanied with some new repository secrets that grant access to the dockerhub account
DOCKERHUB_USERNAME
DOCKERHUB_TOKEN

If people are happy with this then I can also add  a openmc:latest image on pushes to master branch

### CODE REVIEW

**Comment by paulromano** [comment]
@Shimwell This would be great. By all means, please push forward and let me know what you need from me to support. Seems like we should have `openmc:develop` that matches the `develop` branch and `openmc:latest` that matches the `master` branch.

**Comment by Shimwell** [comment]
I was just hoping that the additional trigger (on PR with develop) would trigger the github actions so I could see this working before it is merged into develop.

But it appears that PR from fork [doesn't trigger](https://github.community/t/run-a-github-action-on-pull-request-for-pr-opened-from-a-forked-repo/16054) git actions as a security feature.

So I removed that additional trigger. I would be nice to see this running before hand but I think the only way we can do that is to PR from a repo branch (not a fork) or merge to develop and hope the triggers work.

Also I'm not able to check the [secrets have been added](https://docs.github.com/en/free-pro-team@latest/actions/reference/encrypted-secrets#creating-encrypted-secrets-for-a-repository) for a DOCKERHUB_USERNAME and a 
DOCKERHUB_TOKEN

I have added a dockerhub build for merges to the master brnach called openmc:latest

**Comment by pshriwise** [comment]
@Shimwell this is great! Thanks for adding this. It would be nice to combine some of these common steps in the workflow, but sadly it doesn't look like GH is supporting the use of [templates for workflows yet](https://github.com/actions/starter-workflows/issues/245). Another solution might be to write our own [local GitHub action](https://docs.github.com/en/free-pro-team@latest/actions/creating-actions/creating-a-docker-container-action) for this, but I think for the sake of simplicity it would be best to leave that investigation for later.

**Comment by pshriwise** [comment]
One other note is that it would be great to add automated pushing on creation of new version tags. It looks like our [last version](https://hub.docker.com/r/openmc/openmc/tags) pushed to dockerhub was `v0.10.0`.

**Comment by Shimwell** [comment]
I think this version tagging is possible, I have just not done it before. Give me a few days to look into it as I think I need to make a new example / test repo. I shall get back to you on that.

**Comment by Shimwell** [comment]
Here is the minimal example repository that I've made to show that a release can trigger a github action and subsequent dockerhub image upload 
https://github.com/Shimwell/example-dockerhub-upload

As you can see from the dockerhub there are three images for this repo, one develop, one latest and one with the release version number 
https://hub.docker.com/repository/registry-1.docker.io/shimwell/example-dh-upload/tags?page=1

**Comment by Shimwell** [comment]
This new .yml should trigger on releases and assumes a tag of v*.*.* 
It should trigger from the next release onwards. 

I have added @pshriwise  and @paulromano  to the[ example repository j](https://github.com/Shimwell/example-dockerhub-upload)ust in case you want to make a release, push to develop, push to main all of which trigger the Github actions.

**Comment by paulromano** [comment]
@Shimwell I've added `DOCKERHUB_USERNAME` and `DOCKERHUB_TOKEN` secrets on the openmc repo here. Are there any further changes you need to make on this branch or should it work as is?

**Comment by Shimwell** [comment]
Thanks @paulromano  that should be all that is needed

**Review by paulromano — APPROVED** [review]

**Pull request merged**
