### PR TITLE
Initial implementation of IncidentProton so cross section data can be plotted

### PR DESCRIPTION
**Pull request by SamPUG**
This pull request contains changes related to #1517.

This PR adds a new `IncidentProton` class which is based on the `IncidentNeutron` class. 
This class allows the user to create an HDF5 file using Proton data from ACE or ENDF libraries. Conversion from ENDF requires the use of the `from_njoy` method which runs the ENDF file through NJOY to re-tabulate cross sections.

Some changes have also been made to `openmc.plotter.py` to allow it to plot proton cross sections. A `particle_type`  argument which can be set to proton for proton handling. The default is still neutron. Initial energy limits for plotting were chosen to encompass the range of energies seen during testing. 

I have done most of the testing of these developments using the TENDL-2019 library. The ace version of TENDL-2019 includes example plots of included data. I have inspected a range of hdf5 files to confirm that they have the correct format. I have also plotted cross sections from libraries generated from both ACE and ENDF files and compared them with the TENDL references where appropriate. The IncidentProton class and plotter additions seem to be working as expected. 

I haven't added any unit tests as there is no proton data in the code release by default. As this is an initial implementation i suggest that unit tests probably aren't required at this point.

### CODE REVIEW

**Comment by paulromano** [comment]
@SamPUG Just wanted to check in on this PR. Do you plan on continuing work on this?

**Comment by SamPUG** [comment]
> @SamPUG Just wanted to check in on this PR. Do you plan on continuing work on this?

Hi Paul. Unfortunately I don't have time to look back into this at the moment so I don't  have any plans in the short term.

**Comment by Shimwell** [comment]
Thanks for getting back to us @SamPUG , do you happen to know if anyone one else from the team is looking into it.

**Comment by SamPUG** [comment]
> Thanks for getting back to us @SamPUG , do you happen to know if anyone one else from the team is looking into it.

I don't think anyone else is looking into this.

**Comment by paulromano** [comment]
Closing this due to inactivity. If there is still interest in adding capability for reading proton (or other charged particle) data, feel free to reopen a new PR or start an issue.

**Pull request closed without merging**
