### PR TITLE
Fix reading source file with time attribute

### PR DESCRIPTION
**Pull request by paulromano**
This PR addresses an issue identified by @yrrepy in #2223. It's a one-line fix, but I've gone one step further to add a test that would have caught it in the first place.

### CODE REVIEW

**Review by gridley — APPROVED** [review]
LGTM!

**Review by gonuke — CHANGES_REQUESTED** [review]
I don't see how this test actually tests anything?  The test reads `source.h5` but the PR adds a file with a different name (presumably this new file has a `time` attribute in the source).  Should the test be reading this new source file?

**Comment by gonuke** [comment]
Is this related to @ypark234 's addition of surface source read/write?

**Review by gonuke — APPROVED** [review]
LGTM!

**Pull request merged**
