### PR TITLE
Mcf example using paramak cad

### PR DESCRIPTION
**Pull request by Shimwell**
This PR is an attempt to add a magnetic confinement fusion example to the collection of Jupyter notebook examples

This attempts to duplicate the style used in @pshriwise DagMC [example notebook] (https://github.com/openmc-dev/openmc/blob/develop/examples/jupyter/cad-based-geometry.ipynb)

The dagmc.h5m model was made using the Paramak and the details of that model creation can be found [here](https://github.com/Shimwell/fusion_example_for_openmc_using_paramak/) The url downloads the dagmc.h5m model from this repo but I notice that the DagMc example used a tiny url so perhaps this can be changed if preferred.

Minimal tallies have been added (TBR cell and tritium production mesh)

### CODE REVIEW

**Comment by Shimwell** [comment]
I notice a small conflict as I updated the Trelis link to Coreform in the DagMC example, what do you think @pshriwise

**Comment by Shimwell** [comment]
Also I have a nice picture of the model that could be added to the notebook if anyone likes that idea

reactor

**Comment by paulromano** [comment]
@Shimwell This looks like a really cool notebook! I put the "on hold" label on this PR for now while we try to sort out where we want to have our Jupyter notebooks end up.

**Comment by Shimwell** [comment]
I think this can be closed now that we have the notebooks wiki https://github.com/openmc-dev/openmc/wiki/Example-Jupyter-Notebooks

**Comment by paulromano** [comment]
@Shimwell Yes! Let me know where I should link to and I can add it on the wiki page.

**Comment by Shimwell** [comment]
Thanks @paulromano 

This link would be great https://github.com/Shimwell/fusion_example_for_openmc_using_paramak

**Pull request closed without merging**
