### PR TITLE
Toggle Feature and IUPAC abundance data update

### PR DESCRIPTION
**Pull request by quantaroo**
# Description

Perry and I suggest that the current approach, which selects column 6 of IUPAC 2013 when an interval is present in column 9, is incorrect. We propose two alternating approaches: reverting to IUPAC 2009 and using its column 9 or continuing with IUPAC 2013 but using the average (mean) when an interval is present in column 9. 

Reference: https://github.com/openmc-dev/openmc/issues/2423

Fixes # (issue)

I made the adjustments by taking the intervals onto an excel sheet and averaged the appropriate intervals in IUPAC 2013. 

I then updated the adjusted numbers with the current data in openmc.

I took the previous data for IUPAC 2009 from previous openmc versions 

I made an environment variable that can be set in the python api before import openmc

examples:

Togglepy

Toggledata

# Checklist

- [yes] I have performed a self-review of my own code
- [] I have run [clang-format](https://docs.openmc.org/en/latest/devguide/styleguide.html#automatic-formatting) on any C++ source files (if applicable)
- [yes ] I have followed the [style guidelines](https://docs.openmc.org/en/latest/devguide/styleguide.html#python) for Python source files (if applicable)
- [ ] I have made corresponding changes to the documentation (if applicable)
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)

### CODE REVIEW

**Comment by gridley** [comment]
I do agree that it would be nice to have a little more control in choosing isotopic abundances of elements.

What I don't agree with is that this is the right way to do it. If using the interval definitions, what would *really* be nice would be the ability to generate a representative sample element using isotopic abundances that fall within the listed intervals. Of course, choosing the average case is a simple subset of this generalized capability. Then, by default, the best measurement would be used. In the absence of other information, using the average of the interval doesn't make sense to me. It could be the case that the interval is meant to cover the various naturally occurring extremes of isotopic abundances, and in that case, taking the average could be extremely inaccurate.

It could be that 99% of the time some abundance of an isotope is 0.01% and 1% of the time the abundance is 100%. In that case the average is never close to a given sample, whereas using a single "best" measurement will be close to a sample a reasonable amount of the time. This is the case in, for example, C14, where the distribution of its abundances in materials is bimodal. One mode of the distribution is for alive stuff, and other leg of the distribution is for dead stuff. Neither is close to taking the average.

Then people could estimate the sensitivity of their results to isotopic ratios of their materials. I imagine this could be a non-negligible effect in activation problems. That would be super cool, and not too hard to implement given what you already have here. What do you think?

**Comment by yrrepy** [comment]
Ideally the user could select an abundance database and atomic mass database to read in, likely coupled.

Gavin, I think to your point about bimodal C14, Lithium 6/7 is a good example, the average giving a strange %.
AME2020/NUBASE2020, which OpenMC is using as the default atomic mass database, uses the interval average.
https://www.anl.gov/phy/atomic-mass-data-resources
https://www.anl.gov/phy/reference/nubase-2020-nubase4mas20
https://www.anl.gov/sites/www/files/2022-11/nubase_4.mas20.txt
It makes the most sense to default to what the reference database is doing, rather than making a new way.

Really I would say both approaches for IUPAC-2013 are unsatisfying.
We have put in IUPAC-2009, albeit not as the default, as I think it is actually the best solution: an educated/representative guess of what material/abundance someone is most likely to encounter.
IUPAC-2013 moved to intervals, but NIST has stuck to IUPAC-2009 individual representative values.

Almost all other databases still use IUPAC-2009.

**Review by paulromano — CHANGES_REQUESTED** [review]
@quantaroo Thanks to both you and @yrrepy for proposing this fix/change and apologies I haven't chimed in on the discussion thus far. My thoughts are as follows:

- For the 2013 data, I agree that when an interval is present, we should use the mean of the interval since this is consistent with NUBASE2020.
- Updating the 2013 values will likely result in some test failures, so you should go through and update any tests that need updating (see our developer's guide section on the [test suite](https://docs.openmc.org/en/latest/devguide/tests.html))
- I am personally not convinced that we should provide the IUPAC 2009 data. If someone has an application that is sensitive to the exact values (e.g., the H2 abundance) they should just specify everything by nuclide to be explicit. To @yrrepy's point in #2423 that many databases still use the 2009 data, my guess is that those databases are simply just dated and it wasn't a conscious choice to use 2009 instead of 2013.
- A user who _really_ wants to use the 2009 data does have the option of monkey-patching the `NATURAL_ABUNDANCE` dictionary.

I would recommend you break this PR into two separate PRs: one updating the 2013 values to use the interval means and corresponding test updates (which I hope we can all agree on), and a second one proposing to add the 2009 data as an option.

**Comment by yrrepy** [comment]
IUPAC-2009:
I generally prefer explicitly stating my nuclides, having pre-determined them before building the MC input.
But there are cases where automation comes into play and can be much easier to stick to a database.
Almost all other neutronic databases use NIST, which is IUPAC-2009; which makes things tedious when cross-comparing and OpenMC can't select NIST, nor can the other code use IUPAC-2013. (Though I suppose such could be constructed in the case of LANL ISC and mattool).


IUPAC-2013:
I just noticed an issue with the interval averaging and NUBASE2020; take a look at Oxygen and Sulphur.
With this method the nuclides in certain element species do not sum 100%, due to having 3+ isotopes and I guess intervals not from equivalent measurements.

I agree splitting the PR makes sense.

**Comment by paulromano** [comment]
@yrrepy Interesting point about oxygen and sulfur. It appears to affect magnesium as well.

**Comment by gridley** [comment]
I was unaware that this interval averaging approach is standard! Apologies to come in here and complain about it. 😄 

I wonder if there are any studies that quantify whether this is in fact the most often correct method, though. I still suspect that the average error of using a single best measurement is lower than using the average measurement.

For comparison to other codes alone, that's a nice feature to have!

**Comment by quantaroo** [comment]
I have created the two new PR as requested
Reference: https://github.com/openmc-dev/openmc/pull/2586 and https://github.com/openmc-dev/openmc/pull/2585

**Comment by paulromano** [comment]
Closing this in favor of #2585 and #2586

**Pull request closed without merging**
