### PR TITLE
Replace centroid() with vertex_average().

### LINKED ISSUE #1914: Elem::centroid() is now deprecated in libMesh
`Elem::centroid()` is now deprecated in libMesh. To prepare for this capability being removed in the future (as well as hide a warning message that currently prints out), `centroid()` should be replaced by `vertex_average()`. This new function has the exact same underlying behavior, just a different name.

### PR DESCRIPTION
**Pull request by aprilnovak**
Replace `centroid()` with `vertex_average()` to prepare for future deprecation.

Closes #1914

### CODE REVIEW

**Comment by paulromano** [comment]
Looks like CI is failing because the version of libmesh is pinned at 1.6.0:
https://github.com/openmc-dev/openmc/blob/f0aa6664b3d6836baf688f53267a5fa301693279/tools/ci/gha-install-libmesh.sh#L8

**Comment by aprilnovak** [comment]
I did notice that yesterday and force pushed with that file changed - it looks like CI is now pulling 1.6.2, but still not passing...

**Comment by pshriwise** [comment]
When looking at the release notes for libMesh, I don't see this switch happening until [`v1.7.0` ](https://github.com/libMesh/libmesh/blob/v1.7.0-rc3/NEWS). 1.7.0 is still pending release as `v1.7.0-rc3`. Looks like we'll need to wait a bit until we can check out the stable `v1.7.0` version of libmesh in CI?

**Comment by paulromano** [comment]
@aprilnovak It looks like this PR could be revived now that libmesh 1.7.0 (and 1.7.1) have been released. Do you want to take a shot at updating this?

**Comment by aprilnovak** [comment]
Sure thing! Will get to this soon.

**Comment by paulromano** [comment]
Just wanted to ping you on this @aprilnovak. We're going to try to get a release out soon -- probably would make sense to include this in the release too

**Comment by aprilnovak** [comment]
Is there something else that needs to be done on this PR? I updated it 2 weeks ago and I believe it's ready-to-go. Sorry for not notifying you at the time, figured you'd do another sweep :)

**Comment by paulromano** [comment]
Sorry for the noise, I didn't realize you had updated this :smile: As we discussed offline, let's hold off on merging this until after we do a release.

**Review by paulromano — APPROVED** [review]

**Pull request merged**
