### PR TITLE
Move thermal scattering data to C++

### PR DESCRIPTION
**Pull request by paulromano**
In preparation for some refactoring of the thermal scattering data, I've translated the relevant types from sab_header.F90 to C++ (thermal.h):
- `SAlphaBeta` -> `ThermalScattering`
- `SabData` -> `ThermalData`
- `DistEnergySab` -> `ThermalData::DistEnergySab`

The renaming reflects the fact that for thermal elastic scattering, we don't actually deal with S(a,b). I've added a new `CoherentElasticXS` function type in endf.cpp that, while not used currently, will be used in the refactor (for storing the thermal elastic cross section). Since thermal scattering data was the last thing that relied on `CorrelatedAngleEnergy`, I was able to completely remove secondary_correlated.F90 and angleenergy_header.F90.

One unrelated change in this PR: I've added a [pyproject.toml](https://www.python.org/dev/peps/pep-0518/) file that indicates to pip what the build dependencies of OpenMC are. So, now if you `pip install .` in the OpenMC directory, you don't need to have numpy and cython already installed (it figures this out automatically based on pyproject.toml).

### CODE REVIEW

**Comment by smharper** [comment]
Also, you'll need to resolve a small conflict with recently changed indentation in xml_interface.h

**Comment by paulromano** [comment]
Thanks for pointing out the conflict; I just merged develop in.

**Comment by paulromano** [comment]
That is strange. It looks like the most recent [build](https://travis-ci.org/openmc-dev/openmc/builds/416987702) passes fine, but GitHub doesn't see it. I'm ok with you manually merging.

**Comment by paulromano** [comment]
The results are for a merge commit between the branch (74c8d7) and develop (c56b91), hence why it doesn't appear to be on the branch. But I see what you're saying -- when I merged develop into this branch, it never reran.

You can try merging from the command line or I can temporarily disable the status check requirement. Let me know what you prefer.

**Comment by smharper** [comment]
GitHub rejects the command line push as well.  Looks like we really have to disable the CI check.  Feel free to hit the merge button yourself.

**Pull request merged**
