### PR TITLE
Export materials.xml from depletion results

### PR DESCRIPTION
**Pull request by rockfool**
This PR tries to export materials.xml file from previously simulated depletion results. 
Per the comments from @drewejohnson and @gridley , I came up with another solution based on depletion result file like this:

`#Get result file
results = openmc.deplete.ResultsList.from_hdf5('depletion_results.h5')
time_step = results.get_eigenvalue()[0]/3600/24 # unit:day
print(time_step) # print cumulative time step for check

#Load geometry from statepoint
statepoint = 'statepoint.##.h5'
with openmc.StatePoint(statepoint) as sp:
    mats_list = sp.summary.materials

#nuclides list to evalulate 
nuc_with_data = get_nuclides_with_data()

#get the nearest EFPD to the desired value 
val_efpd = 1499.0 
burnup_index = np.abs(np.asarray(time_step)- val_efpd).argmin()

#export to materials.xml 
results.export_to_materials_xml(mats_list, burnup_index, nuc_with_data)
`
So in this solution, user could define the nuclides list of interest according to the "cross_sections.xml" by himself. 
And the search of nearest EFPD or depletion step could be also controlled by user. However, I am not sure how to prepare those non-depletable materials without in depletion file. I just had the idea to obtain them from statepoint file.  
Any thought? @drewejohnson @gridley

### CODE REVIEW

**Comment by paulromano** [comment]
Although we may want to allow the list of nuclides to be configurable, we _definitely_ need to have a default behavior that does not put the onus on the user to identify the set of nuclides. My sense is that the most common use case would be a user just wanting to reconstruct the state of the simulation at a given point in time and they just want the list of nuclides to match what was used in their original depletion simulation.

Also something to consider (in case it has been overlooked) -- the depletion results file only contains depletable materials. We'll still have to pull in the non-depletable materials from somewhere.

**Comment by drewejohnson** [comment]
@paulromano raises two excellent points. 

Could we leverage [`openmc.Summary`](https://docs.openmc.org/en/latest/pythonapi/generated/openmc.Summary.html) to obtain both the non-burnable materials and nuclides with data? The API looks a little smaller too, since we don't care so much for tallies in this particular instance. Plus, the `materials` and `nuclides` attributes could be helpful

https://github.com/openmc-dev/openmc/blob/e91a6aac1786a5f391330a599ac81345d2af4781/openmc/summary.py#L23-L27

An alternative way to find all nuclides with xs data could look something like
```python
names = set()
library = openmc.data.DataLibrary.from_xml()
for lib in library.libraries():
    if lib["type"] in {"neutron", "photon", "wmp"}:
        nuclides.update(lib["materials"])
```

By default, `openmc.data.DataLibrary.from_xml` will pull from `OPENMC_CROSS_SECTIONS`, but explicitly pass in the environment variable just for a little more future proofing.

I also wonder if we want to directly export to xml or return a full `Materials` instance which in turn can be exported to XML. Directly exporting might be useful for the majority of use cases, but if you wanted to do further inspection and/or change the name of the exported material file working directly with the `Materials` instance would be preferable

For what it's worth, I think specifying an integer index for the burnup step is fine. We can leverage #1713 to give users an easier way to find a depletion step of interest

**Comment by rockfool** [comment]
Thanks for your comments. I plan to revise it based on your comments.
1. If nuc_with_data is none by default, "OPENMC_CROSS_SECTIONS" will be used to get nuc_with_data just as mentioned by @drewejohnson ; 
2. I was also thinking of export_to_materials_xml returning materials instead of xml file. By this, materials extracted from depeltion result can be easily modified at user's request. So the function name could be "extract_to_materials" 
3. Keep the index of burnup step as is. If possible, how to get index of burnup step from EFPD could be presented in a demo script. 
4. I am not sure if using statepoint file or summary file to get non-burnable materials. Currently, I just put onus to user. Can we do it like this? If mats_list is none by default, only the depletable materials will be extracted. If statepoint or summary file is provided, the mats_list will be passed from statepoint or summary file. And one more question, which file is better?

**Comment by drewejohnson** [comment]
To respond in the same form @rockfool 

1. Pulling from `OPENMC_CROSS_SECTIONS` seems like a reasonable default if no nuclides are provided. We are pretty clear that this environment variable should be set, and it's reasonable for me to assume it will exist in many situations.

2. :+1: for exporting to a `Materials` instance

3. :+1: especially if we add something in the examples for how to obtain this information

4. Getting the non-burnable materials require some thinking, but I believe we should make the effort to provide this data to the user without any user actions. For someone without the level of familiarity that we have, this might feel like an impossible task. But I think we can make it work.

To the point of _how_ to get this data, I think the `Summary` file is our best bet. I did some brief testing, and we can obtain a full `Materials` instance from the `Summary.materials` instance as the docs indicate. The question would be if those compositions reflect the beginning-of-life compositions before depletion, or the results from the final depletion simulation. However, since we're only extracting materials that, by definition, will have constant compositions through depletion, that doesn't matter to much. If we can generate a collection of `Material` instances from a `Result`, then we can compare what materials were found in the depletion file, and what exist in the `Summary`.

**Comment by drewejohnson** [comment]
After some thought, if we're going to pull the nuclides from `OPENMC_CROSS_SECTIONS` or some user-provided set, then we don't _need_ the summary file. We can pull materials from `materials.xml` if it's available.

I wonder if we could provide some `Materials.update` or `Materials.merge`-like method where given two `Materials` instances, you update in-place the former with the contents of the latter. Then, we and/or end-users can do something like
```python
# Non-burnable materials and beginning-of-life burnable materials
beginning = Materials.from_xml("materials.xml")
# or beginning = Summary("summary.h5").materials
res = ResultsList.from_hdf5("depletion_results.h5")
burned = res[j].<TBD Materials method>() 
beginning.update(burned)
beginning.export_to_xml("burned_materials.xml")
```
Thoughts?

**Comment by paulromano** [comment]
@drewejohnson I like your last proposal there. I was also going to mention that there is no guarantee that summary.h5 is generated because a user can turn that off. A materials.xml file on the other hand will always be generated at the beginning of depletion.

**Review by drewejohnson — CHANGES_REQUESTED** [review]
Please see comments in #1726 regarding the inner iteration and testing

**Comment by rockfool** [comment]
Thank all for your comments, and I have talked with Gavin @gridley and he will take it over and improve it in his separate PR #1726. So I close this at current status.

**Pull request closed without merging**
