### PR TITLE
Fix compilation on CentOS 7 (missing link to libdl)

### LINKED ISSUE #2848: Compilation failure on CentOS 7
## Bug Description

Compilation fails on CentOS 7 at link time with the following messages (pardon my French):
```
lib/libopenmc.so : erreur : référence à « dlclose » non définie
lib/libopenmc.so : erreur : référence à « dlopen » non définie
lib/libopenmc.so : erreur : référence à « dlerror » non définie
lib/libopenmc.so : erreur : référence à « dlsym » non définie
collect2: erreur: ld a retourné le statut de sortie 1
```

## Steps to Reproduce

Build vanilla OpenMC.

## Environment
- CentOS 7
- custom environment modules are used to provide the following software:
  - gcc 9.3.0
  - curl 7.78.0
  - cmake 3.25.0
  - szip 2.1.1
  - hdf5 1.12.1 (serial)

### PR DESCRIPTION
**Pull request by arekfu**
# Description

This PR fixes compilation on CentOS 7.

Fixes #2848.

# Checklist

- [x] I have performed a self-review of my own code
- [ ] ~~I have run [clang-format](https://docs.openmc.org/en/latest/devguide/styleguide.html#automatic-formatting) (version 15) on any C++ source files (if applicable)~~ (not applicable)
- [ ] ~~I have followed the [style guidelines](https://docs.openmc.org/en/latest/devguide/styleguide.html#python) for Python source files (if applicable)~~ (not applicable)
- [ ] ~~I have made corresponding changes to the documentation (if applicable)~~ (not applicable)
- [ ] ~~I have added tests that prove my fix is effective or that my feature works (if applicable)~~ (not sure this is possible?)

### CODE REVIEW

**Comment by HunterBelanger** [comment]
Hi @arekfu, have you tried to see if using the `CMAKE_DL_LIBS` works instead of adding `dl` directly (see [here](https://cmake.org/cmake/help/latest/variable/CMAKE_DL_LIBS.html)) ? In theory this should allow it to play nice with all operating systems.

**Comment by arekfu** [comment]
Hi @HunterBelanger, thank you for this suggestion! I was actually not aware of `CMAKE_DL_LIBS`. Let me test this...

**Review by paulromano — COMMENTED** [review]
I'm a little confused by this. <s>OpenMC does not make any direct calls to `dlopen` or other functions from `libdl`, so it must be a transitive dependency from one of the libraries we explicitly depend on. In that case, it should be the responsibility of whatever library is actually using it to make sure that the dependency on `libdl` propagates through.</s>

Also side note that CentOS 7 is EOL in six months :hourglass:

EDIT: looks like I spoke too soon. We do use `dlopen` for loading custom source libraries, in which case it _is_ appropriate to be linking against libdl.

**Comment by arekfu** [comment]
Hi @paulromano, I am aware that time is ticking for CentOS 7, but I think that the fix is valid for other platforms, too. I'm more worried about the failing checks. Is that expected?

**Comment by paulromano** [comment]
@arekfu There is an issue with a new release of scipy that is causing failures in CI. We just merged another PR that restricts the version of scipy for now, and I've just updated your branch to incorporate that. Hopefully tests should be passing now :crossed_fingers:

**Review by paulromano — APPROVED** [review]
Tests passing now. Thanks @arekfu!

**Pull request merged**
