### PR TITLE
use E_rel to sample secondary angle dist

### PR DESCRIPTION
**Pull request by walshjon**
The relative neutron-nucleus energy needs to be used to sample 0 K secondary angular distributions (as opposed to the lab frame neutron energy).

### CODE REVIEW

**Comment by nelsonag** [comment]
@walshjon While the change you made makes sense from a physical sense, I have to wonder if this change would make our sampling method inconsistent with the measured + evaluated nuclear data (at least at measurement [typically room] temperature).  

More specifically, do you know if the measurement processing and evaluation phases include adjustments to the discrete f(mu) that are measured based on temperature or not?  If they do, then is in the direction of goodness.  If they don't, then I guess all I could say with certainty is that the old way would at least produce roughly the same average scattering behavior at measurement temperature.

**Comment by walshjon** [comment]
@nelsonag Thanks for thinking about this.

It's my understanding that all measured data, including distributions, are **supposed** to be corrected to 0 K from their measured temperature when producing an evaluated nuclear data file.  If the evaluator does their job well, this code change is unambiguously better physics.

If the distributions are erroneously given as a function of lab frame neutron energy in a material at some non-zero temperature, this change introduces an inconsistency for simulations performed at exactly that non-zero temperature, as you say.  For non-0 K evaluations, there is already an inconsistency for all simulations performed at temperatures other than the measurement temperature.  The question then becomes: is it better to assume the evaluations are 0 K and use the relative energy, or is it better to assume the measurement temperature is close enough to our simulation temperature that the effective distributions are identical?  I'd guess the former produces better physics the majority of the time.

Frankly, this doesn't matter unless secondary distributions change over energies on the order of ~kT.  This doesn't occur in the vast majority of current evaluations/reactor temperatures, but could if secondary distributions are reconstructed from resonance parameters.  And, since the parameters should be at 0 K, this change would be the right thing to do.

**Comment by smharper** [comment]
I think the lab frame is the correct one.  Take a look at ENDF-102 section 6.2 in the LCT description.  It says, "incident energy is always given in the LAB system".

**Comment by walshjon** [comment]
My read of that is that they're distinguishing between LAB and CM.  The data is 0 K, so you want to use E_rel in order to sample it with the correct incident "LAB" energy.  I.e., E_rel is E_lab if the laboratory is managed by a 0 K target nucleus.

**Comment by walshjon** [comment]
Interestingly, it looks like ENDF-6 doesn't actually require 0 K angular distributions, although I think most evaluations are.  Per Sec. 4.2.1:

"Note that T and LT refer to temperature (in K) and a test for temperature dependence,
respectively. These values are normally zero, however."

**Comment by smharper** [comment]
Ah, right.  I'm on the same page as you now.  Yes, I would hope that all ENDF evaluations use 0K or at least that NJOY corrects them to 0K.

I must say I'm also a smidgen confused how `dot_product(v, v)` gives us an energy.  I guess we're doing our physics in a system where the neutron mass is arbitrarily set to one (hence atomic weight ratio), but I don't know how the 1/2 of the old E = 1/2 * m * v^2 gets included here.  Is it the case that everything we call a velocity is actually velocity/sqrt(2)?  Anyway, I'm willing to blindly accept it since that's how all the energy/velocity calcs are down in physics.F90.

@walshjon, do you know how to update the test results with our new test system?  I believe you can just do a `pytest --update` in the tests directory.

@paulromano, we should probably check this against our benchmark suite just to be safe.  Do you have a quick script you can run to give us our new deviations?

**Comment by walshjon** [comment]
I always have to re-check the algebra on that, too, but it does work out.  The energies are always as you'd expect, but we usually just call sqrt(E) a velocity.

I haven't updated using this testing framework.  pytest doesn't seem to take --update.

I agree about the benchmark suite.

**Comment by paulromano** [comment]
I have thought about this issue before and I'm not sure there's a clear-cut answer. I'm not at all convinced that the data in ENDF is actually 0K data. If it were, there would be clear effects from resonances (just take a look at the distributions resulting from NJOY when the option to generate elastic scattering angular distributions based on RML is turned on). The data in ENDF tends to be a lot smoother -- what you would expect if one were to actually "broaden" the angular distributions. There are no compelling studies on this issue that I'm aware of (would make a really nice paper; wanted to do it but don't have a good reason to spend a lot of time on it). Furthermore, most codes I've peeked at do not use the relative energy and instead use the lab energy directly (MCNP and Serpent). I forget what MC21 does but can touch base with my old colleagues there.

As a prerequisite, we would definitely need to understand the impact on critical benchmarks. If it tends to improve results, I'd say sure. Otherwise, I'm not sure it's worth it.

`pytest --update` should work. The `--update` option is a custom flag (if you run `pytest --help` from our repo, you should see it there).

**Comment by walshjon** [comment]
I don't expect any statistically significant effects on the criticals.  This isn't going to matter much except for when finely structured distributions reconstructed from resonance parameters or elevated system temperatures are present.  That said, I have looked at this, and you can see differences in simulations depending on whether you use E_lab or E_rel.

0 K distributions in evaluated data would not necessarily (and don't, as you say) show all of the fine structure that's actually present in nature.  The secondary distributions in most evaluations are indeed smoothed, but that seems to be a result of energy resolution in measurements (i.e., not being able to resolve structure in distributions over the energy width of a resonance) or the product of the model calculations that are sometimes used --- not temperature broadening.  The distributions constructed from resonance parameters are also going to be 0 K.  E_rel needs to be used in that case.

At one point, a few years back now, I saw some MCNP source that used E_rel.

**Comment by paulromano** [comment]
@walshjon Good points. Can one really distinguish between energy resolution and broadening though? Looking at the MCNP 6.1.1 source right now, it appears that the lab energy is used when choosing angular distributions for elastic scattering. Do you happen to know how Mercury handles this? Just wondering if there is any precedent for using the relative energy.

@smharper I do have some scripts for running benchmarks, but both the scripts and the benchmark models themselves are out of date. When I have some free time, I'll try to get them updated.

**Comment by walshjon** [comment]
Your point that, practically, resolution broadened distributions look like temperature broadened cross sections is well-taken.  However, I think the functions used for the convolution (e.g., a Maxwellian) are generally different for each process.  I interpret the smoothed distributions found in most evaluations as interpolable multigroup 0 K data.  That is, they represent the average distributions, at 0 K, for an energy region about the tabulated point.  It's from this interpretation I claim E_rel is the correct one to use.

If we instead interpret them as resolution and/or temperature broadened data, the only time we could treat them correctly is in systems exhibiting the same resolution/temperature broadening characteristics as the experiment, as @nelsonag pointed out (*E_lab* would be correct in this case).  It would be ambiguous how to treat them under all other system conditions.

It's actually even less clear how to handle this with ENDL data.  With GND and its new collision physics pacakge, the plan is to use E_rel, though.

**Comment by smharper** [comment]
@walshjon's quote from ENDF-102 sec 4.2 is pretty compelling.  I also took a look at the file 4 data for U-238 and H-1, and I confirmed that is indeed at 0K (ENDF/B 7.1).

I think we should switch to E_rel as long as there is no difference in the cold criticals (highly doubt there will be).  It seems to be the model the evaluators intend for us to use, even if other MC codes haven't adopted it

**Comment by paulromano** [comment]
Yeah, I'm coming around to the argument too. At the end of the day, we should implement the physics that the evaluators specify, even if the data is "wrong" (for example, if the distribution were temperature broadened even though it says 0 K). I also talked to some of my collaborators at ORNL (@sphamil and by extension @sobesv) and they are in agreement that the relative energy should be used (although they, too, don't do that in their codes as of yet if I understand correctly).

@walshjon For this PR to proceed, you'll need to update test results. I'd also like to compare results on critical benchmarks before we merge but haven't had the time to do it.

**Comment by walshjon** [comment]
Whatever brings you into the fold @paulromano !  Without re-stating the physics considerations, I'll just re-emphasize my personal motivation for the change is that it's an unambiguously better physics choice (not just following evaluator orders) under the conditions where temperature-dependent distributions could have any meaningful impact.

I can give the pytest update another shot.

**Comment by paulromano** [comment]
No action on this change for a while so I'm going to close it. I would like to get this change in since I think all of us agree that from a physics perspective it makes more sense. However, to be sure, I'd like to see a comparison on critical benchmarks with and without the change so that we truly understand the aspect. @amandalund and I are planning on setting up some scripts for automated validation/cross-code comparison on benchmark models, so once we have something up and running, it should be straightforward to see the impact of this change.

I'll open an issue so we don't forget about this.

**Pull request closed without merging**
