### PR TITLE
Populating C-side cell id->index map.

### PR DESCRIPTION
**Pull request by pshriwise**
This PR adds the population of `cell_map` for use on the C++ side.

### CODE REVIEW

**Comment by smharper** [comment]
I've fixed the cell map in my `cpp_tallies` branch.  If you don't mind the wait, I'd rather not merge this so I can avoid the conflict with that branch that I hope to PR soon.

**Comment by pshriwise** [comment]
@smharper sure thing. I'm relying on this change in my branch moving plotting capabilities to C++, but I won't be PRing that until next week as I'm traveling right now. I can bring in your change later.

**Comment by shikhar413** [comment]
Hi @pshriwise, I just noticed that you mentioned you were working on moving plotting to C++. I made some initial headway on this as well but got caught up working on some other things instead, and it seems like you've made more progress than I have. Wanted to check that you were planning to complete the plot conversion to C++ instead of duplicating efforts.

**Comment by pshriwise** [comment]
@shikhar413 that's correct. I'm going to do some cleanup on it early next week and submit a PR. Sorry about the duplicated effort. It should be done soon though! I'll add you as a reviewer when the time comes.

**Comment by shikhar413** [comment]
Got it, no worries about that.

**Comment by paulromano** [comment]
@pshriwise Can this PR be closed with the merging of #1101?

**Comment by pshriwise** [comment]
@paulromano yup! Closing now...

**Comment by smharper** [comment]
Thanks for the favor, @pshriwise!

**Pull request closed without merging**
