### PR TITLE
Rational univariate distribution

### PR DESCRIPTION
**Pull request by ojschumann**
Implementation of a univatiate distribution with a pdf of p(x) = x^n

Usefull for samplig homogenous cylindrical or spherical sources
Simmilar to MCNPs "sp -21 n" functionality

can be used as follows (for spherical sources, n=2 is needed)

settings.source = openmc.Source(
                               space=openmc.stats.SphericalIndependent(
                                  r     = openmc.stats.Rational(1,3,2),
                                  theta = openmc.stats.Uniform(0, pi),
                                  phi   = openmc.stats.Uniform(0, 2*pi)))

### CODE REVIEW

**Comment by paulromano** [comment]
@ojschumann Thanks for this PR! It looks like there is overlap between this PR and the other one you submitted, #1882 (the `Rational` distribution appears in both). How would you like us to handle these?

**Comment by ojschumann** [comment]
Hi @paulromano

obviously my first try with a git pull request did not work out very well ;-) 

My feeling was, it might be better to send two PR, one which implements an already documented feature (the mixture) and one PR with a completely new feature. Thus I think it is best to strip the Rational distribution from #1882  (I can see, that it has two commits instead of my intended one). Can I modify the PR and remove one commit?

**Comment by paulromano** [comment]
Ok, I thought that was perhaps what you had intended :) Yes, please go ahead and strip the rational distribution from the other PR.

**Comment by ojschumann** [comment]
So I did. And recognized, that I need to reed, how the git-workflow should be used. Sorry about that.

**Comment by paulromano** [comment]
No worries, we all have a few bumps in our first pull requests! Really appreciate the contributions -- I'll try to review today or tomorrow.

**Pull request closed without merging**
