### PR TITLE
updated checkout action to v3

### PR DESCRIPTION
**Pull request by shimwell**
I noticed the CI was failing with this error message

```bash
Python 3.10 (omp=n, mpi=n, dagmc=n, ncrystal=n, libmesh=n, event=n vectfit=n)
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
```

This PR updates the checkout action to use v3 instead of v2

### CODE REVIEW

**Review by paulromano — APPROVED** [review]

**Comment by shimwell** [comment]
I just noticed that I accidentally made this branch on the openmc repo instead of my fork, sorry about that.

I have merged in the latest develop branch (which fixes the CI) and am now rerunning the tests as I think that a pass is required to merge this PR

**Comment by shimwell** [comment]
I have merged in the latest develop branch (which fixes the CI) and am now rerunning the tests as I think that a pass is required to merge this PR

**Comment by shimwell** [comment]
Super tests are passing, I think this is ready to merge

**Comment by paulromano** [comment]
Thanks @shimwell!

**Pull request merged**
