### PR TITLE
Fixed some errors so that mypy openmc can run

### PR DESCRIPTION
**Pull request by christinacai123**

### CODE REVIEW

**Comment by gridley** [comment]
awesome!

**Review by paulromano — CHANGES_REQUESTED** [review]
Thanks for this PR @youngwki! I pulled down your branch and ran `mypy` and I'm seeing a bunch of `Name "...." already defined` errors. It looks like in some cases, the setters were copied but the original ones were not deleted, which is why `mypy` is still complaining about them. Can you go through the changes and make sure any setter that was moved has the original one deleted?

**Comment by paulromano** [comment]
@christinacai123 Just wanted to check in and see if you are planning on updating this PR. I'd love to get this merged but it does need a few fixes first.

**Comment by christinacai123** [comment]
I'm so sorry but I do not plan to update this PR. I'm very busy and hope
that you understand. It was a pleasure working with you and I wish you all
the best.

**Comment by shimwell** [comment]
Thanks for letting us know @christinacai123 and thanks for getting started on this topic. It looks like good progress has been make.

I can fix those name errors and PR to this PR

**Comment by shimwell** [comment]
Fixed a bunch of those errors and made a PR

There are more to fix so I can finish this tomorrow

https://github.com/youngwki/openmc/pull/1

**Comment by paulromano** [comment]
@christinacai123 Thanks for your work on this and wish you the best as well.

@shimwell Thanks for picking this up to get it to the finish line. Can you create a new PR here using your `static_errors_continuation` branch?

**Comment by paulromano** [comment]
Closing in favor of #2557

**Pull request closed without merging**
