### PR TITLE
Fixes angle sampling in CorrelatedAngleEnergy

### PR DESCRIPTION
**Pull request by HunterBelanger**
This fixes a small bug in the sampling of the scattering angle in the `CorrelatedAngleEnergy` distribution. Previously, the angle was always sampled from the angular distribution associated with the closest outgoing energy (regardless of the interpolation). In LA-UR-03-1987 at the top of page 2-47 under the section for ACE Law 61, it is explained that in MCNP, if histogram interpolation is used, the lower bounding energy angular distribution is used, while for linear interpolation the distribution for the closest outgoing energy's distribution is sampled instead.

The difference between considering and not considering the histogram interpolation is quite small, but it is measurable when performing Kolmogorov–Smirnov tests on the angular distribution for ENDF/B-8 evaluation for Si28 (n,n alpha) and (n,np).

The actual bug fix only appears at the changes near line 262 in the original file. Clang-format decided the the rest of the file could also use some touching-up however.

### CODE REVIEW

**Comment by paulromano** [comment]
Thanks for the fix @HunterBelanger! This looks good to me once tests pass.

**Comment by HunterBelanger** [comment]
So I have updated some of the test results, as changing how the distribution is sampled of course has lead to some changes in problem answers. While the depletion tests are passing now, I am not sure I properly updated the `xs_ref` variable on line 52 of `tests/unit_tests/test_deplete_resultslist.py`.

Also, it now appears that the triso regression test is no longer passing. On my system, the test passes, but on the CI server it doesn't for some reason. The problem is a slight disagreement in the correct value of the error on keff for the problem. I can just copy the returned value from the test server and add that to the results file, though I am not sure this is an appropriate way to tackle the problem ?

**Comment by gridley** [comment]
As for the TRISO, it fails on my system as well. I think that's due to a python version difference between the CI server and our machines. I always just push to github and CI there passes.

**Comment by paulromano** [comment]
@pshriwise just pointed out to me that in order for that rebase to _not_ include the offending large file, you need to run `git rebase --onto <new_develop> <old_develop>`. In your case, the following should work:
```
git remote add upstream https://github.com/openmc-dev/openmc.git
git fetch upstream
git rebase --onto upstream/develop 984bc5~
git push -f origin correlated-angle-energy-fix
```
assuming that `origin` is a remote that points to your fork. If you already have multiple remotes for the main repo and your fork, then use those accordingly.

**Comment by HunterBelanger** [comment]
@paulromano I just applied the rebase. Once the CI server gives an it's new result for the TRISO test, I will update that as well. As far as I could tell, that was the only test that was still failing.

**Review by paulromano — APPROVED** [review]

**Comment by paulromano** [comment]
Thanks again for the fix, and congrats on your first contribution here @HunterBelanger!

**Pull request merged**
