### PR TITLE
Fix package_data specification to include pyx files for Cython builds

### PR DESCRIPTION
**Pull request by burberger**
This fixes building of a standalone distributable python package. Without this change, running a package build fails with the following:

```sh
% python3 -m build
...
  File "/tmp/build-env-3c6tysj8/lib/python3.7/site-packages/Cython/Build/Dependencies.py", line 816, in create_extension_list
    for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
  File "/tmp/build-env-3c6tysj8/lib/python3.7/site-packages/Cython/Build/Dependencies.py", line 114, in nonempty
    raise ValueError(error_msg)
ValueError: 'openmc/data/*.pyx' doesn't match any files
```

### CODE REVIEW

**Review by paulromano — COMMENTED** [review]
Thanks for pointing this out @burberger! It looks like we have a line in the MANIFEST.in file that was supposed to catch these, but evidently there's a typo in that line:
https://github.com/openmc-dev/openmc/blob/0424631b4f62ee475e97808e56d6f1a715a13341/MANIFEST.in#L30

Do you want to go ahead and fix that typo in lieu of the change here?

**Comment by burberger** [comment]
Sure, that seems reasonable. Fixed that typo and another like it in the same file. I did some digging into how the python packager works to make sure this is valid in all cases and I'm reasonably confident it is. Beyond that, I noticed there's a number of other warnings produced by MANIFEST.in right now pertaining to nonexistent files that could also be addressed here. The typo is also recorded as a warning, if the others are also fixed this could be checked in CI quite easily.

Warnings in question:
```
reading manifest template 'MANIFEST.in'
warning: no files found matching 'docs/sphinxext/LICENSE'
warning: no files found matching '*.h5' under directory 'examples'
warning: no files found matching '*.png' under directory 'examples'
warning: no files found matching '*.c' under directory 'src'
warning: no files found matching '*.cc' under directory 'src'
warning: no files found matching '*.h' under directory 'src'
warning: no files found matching '*.hpp' under directory 'src'
```

**Comment by paulromano** [comment]
@burberger If you want to go ahead and remove the ones causing the warnings, I'd say go for it. Thanks again for looking through this!

**Comment by burberger** [comment]
Done!

**Review by paulromano — APPROVED** [review]
Thanks @burberger!

**Pull request merged**
