### PR TITLE
Lattice outer universe cell instance support

### LINKED ISSUE #551: Distribcell Tallies in Lattice Outer Universes
It appears that the tallies with a "distribcell" filter on cells in lattice `outer` universes do not work. Although the code runs fine with such tallies, the results array in the tally's entry in the statepoint file is empty.

I recognize that this is a corner case and that it is tough to imagine a case where one would want to use "distribcell" tallies in lattice `outer` universes. However, I could see one use case if one wished to tally in each of the gaps between fuel assemblies, which may be most conveniently defined with the lattice `outer` attribute.

The reason this came up is that I added an `outer` universe to some of my lattices per the discussion with @smharper on #546. When one generates an `openmc.MGXS` library with "distribcell" domains, tallies will be created for those cells in lattice `outer` universes. Everything is fine unless one tries to loop over the domains in the library to perform operations on the `MGXS` or base `Tallies` in downstream data processing (*e.g.*, distribcell tally summations per #550).

### PR DESCRIPTION
**Pull request by pshriwise**
# Description

As the result of a failed data transfer in Cardinal, @aprilnovak and I discovered that cell instancing isn't supported for the use of cells in universes applied as the outer universe of a lattice (`Lattice.outer`). 

This adds to the instancing infrastructure so that these cells are now assigned the correct number of instances (previously zero) in distribcell and cell instance tallies.

This required a few changes:
  - ensure that `count_cell_instances` and `update_universe_cell_count` is called for the outer universe of lattices
  - add an offset table to `Lattice` to track offsets for distribcells in the outer universe.
  - populate the new `outer_offset_` vector in `Lattice::fill_offset_table`
  - update logic in `distribcell_path_inner` to account for the presence of the new offset array.

Some additional notes:

I considered trying to tie the outer universe offset into the existing `offsets_` attribute of the `Lattice` class, but given the current lattice iterator trouble already present (and addressed in #2921), I decided this would be a better approach.

I've added a case to the `filter_distribdell` regression tests (and did a little restructuring) to test this case. It turns out that the `tally_aggregate` regression test was already applying a `DistribcellFilter` for a cell in an outer universe, but no entries were present in the resulting tally. With these changes, entries appear and the test results needed to be updated accordingly.

No documentation changes were needed, b/c as far as I could see we don't currently call out that cell instance filters aren't possible for cells in outer universes of laticces.

Fixes #551 

# Checklist

- [x] I have performed a self-review of my own code
- [x] I have run [clang-format](https://docs.openmc.org/en/latest/devguide/styleguide.html#automatic-formatting) (version 15) on any C++ source files (if applicable)
- [x] I have followed the [style guidelines](https://docs.openmc.org/en/latest/devguide/styleguide.html#python) for Python source files (if applicable)
- [ ] ~I have made corresponding changes to the documentation (if applicable)~
- [x] I have added tests that prove my fix is effective or that my feature works (if applicable)

### CODE REVIEW

**Review by paulromano — COMMENTED** [review]
Thanks for proposing this change @pshriwise. Conceptually, I'm not sure what to make of including the lattice outer universes for distribcell indexing. If I'm understanding the change here, this would result in **_one_** extra "instance" for cells in the outer universe. However, in most (all?) use cases, the outer universe would result in a whole bunch of extra instances of any cell within the universe. I don't know which is more confusing: providing the user a single result for a cell that appears in the outer universe, or just omitting it altogether.

Do you have a use case in mind that motivates the change here?

**Comment by pshriwise** [comment]
> Thanks for proposing this change @pshriwise. Conceptually, I'm not sure what to make of including the lattice outer universes for distribcell indexing. If I'm understanding the change here, this would result in **_one_** extra "instance" for cells in the outer universe. However, in most (all?) use cases, the outer universe would result in a whole bunch of extra instances of any cell within the universe. I don't know which is more confusing: providing the user a single result for a cell that appears in the outer universe, or just omitting it altogether.
> 
> Do you have a use case in mind that motivates the change here?

Ah yeah, I was thinking that the outer universe is only used once as a background universe, but that's not the case. This would mean we'd need to add instances, and potentially tally bins, on-the-fly as particles enter new instances of the outer universe in the lattice. I can't think of a great way to handle that. We could create a conservative number of outer universe instances by checking the lattice cells against the containing cell boundary, but it wouldn't be trivial to make that robust, especially for hexagonal lattices.

Not important at this point, but the motivation for this PR was more general property mapping for Cardinal. When an outer universe is used and that region is mapped between domains, the properties can't be sent back into the outer universe(s) correctly b/c they don't have entries in the cell instance structures. I think for now we'll treat this as a limitation and do some detection on the Cardinal side for outer universe mapping so we can halt early and report it to the user. It's a useful feature to fill in gaps as needed, but for Cardinal I think we can simply ask users to explicitly define universes for all regions that are being mapped for data transfers.

 Closing this up until greater need arises or we come up with a better solution for handling all instances separately.

**Comment by lewisgross1296** [comment]
If I understand correctly, is the initial motivation so that each `Lattice.outer` layer in a 3D lattice can get a unique temperature by having a unique `(cell ID, cell Instance)` pair? For now, does this limit Cardinal temperature coupling to using 2D lattices, so there can be a unique cell ID for each `Lattice.outer`? 

Just want to start with the right lattice dimension when building future models.

**Comment by pshriwise** [comment]
This has less to do with 2D vs. 3D lattices and more to do with how to handle cell instancing for the `Lattice.outer` universe, which is used to fill any lattice cells outside of the ones explicitly defined in the `Lattice.universes` attribute. 3D lattices should be fine for Cardinal coupling.

The conclusion of the discussion above is that, in a Cardinal problem, any lattice universe in a coupled region of the OpenMC model should be defined explicitly as part of the `Lattice.universes` attribute and coupling in lattice cells filled with the `Lattice.outer` universe considered to be invalid.

**Pull request closed without merging**
