### PR TITLE
Changed xml to lxml

### PR DESCRIPTION
**Pull request by myerspat**
Closes: #2241 

To simplify the python API:
- Converted all `xml` imports to `lxml` in `openmc` and `tests/unit_tests`
- Changed in-code docs to reflect changes in types for `xml` to `lxml`
- Changed write statements to be compatible with `lxml` capabilities
- Removed if import statements for using `lxml` over `xml`
- Changed all `inputs_true.dat` in regression tests to use `<.../>` instead of `<... />`
- Added `lxml` to sphinx requirements

### CODE REVIEW

**Comment by gridley** [comment]
Very nice! I'll give a review once the CI tests are passing.

**Comment by paulromano** [comment]
@myerspat Looks like there are a few tests that rely on libmesh that are [failing](https://github.com/openmc-dev/openmc/actions/runs/4799622413/jobs/8539495516?pr=2489). If you'd like, I can send an update to your branch updating the results for those (if it's too much of a pain to get libmesh installed). There's also a conflict in plots.py you'll need to resolve.

**Review by paulromano — APPROVED** [review]
All looks good to me now -- thanks for this update @myerspat!

@gridley did you still want to look at this before we merge? Don't feel obligated

**Comment by gridley** [comment]
@paulromano , you know what, this is really not a fun one to review with all the repetive changes. If it looks good to you, I believe it!

**Pull request merged**
