### PR TITLE
Source of a Spherical Shell 

### PR DESCRIPTION
**Pull request by cfichtlscherer**
### Implementation of a Spherical Shell Source 

When implementing more sophisticated sources, OpenMC provides the opportunity to define _Custom Parameterized Sources_  which need to be implemented in C++. Implementing them is not that easy, especially for beginners.

I think we could give the users more sources that can be used directly via the Python API.

Here I propose the source of a Spherical Shell which can be used as the following example:
```
source = openmc.Source()
source.space = openmc.stats.SphericalShell((2, 3), (0, 0, 0)) 
source.energy = openmc.stats.Discrete([1e6], [1]) 
source.particle = 'photon'  
```

The first tuple specifies the inner and outer radii of the spherical shell and the second its' center. If the inner radius is set to 0, we get a solid sphere as a source. 

You have to be careful when producing the source points uniformly distributed. I used the math described here:
https://math.stackexchange.com/questions/1111894/random-points-in-spherical-shell

I could add a regression test if there is interest in this feature. For now, I just have plotted the positions of the first 5 000 created points of a Spherical Shell with inner radius 2 and outer radius 3 (Figure) and analyzed their radii.

shell_3d

In addition, I would like to include the source of a hollow cylinder/disk. But first, I wanted to ask how the resonance of such a feature is.

### CODE REVIEW

**Comment by shimwell** [comment]
I think this could potentially be useful for ICF fusion simulations where there might be layers of different temperature / energy neutrons to consider

**Comment by paulromano** [comment]
@cfichtlscherer With the recent addition of the `PowerLaw` class, I believe this could be done with existing classes:
```Python
r = openmc.stats.PowerLaw(r1, r2, 2)
theta = openmc.stats.Uniform(0., math.pi)
phi = openmc.stats.Uniform(0., 2*math.pi)
spherical_shell = openmc.stats.SphericalIndependent(
    r=r, theta=theta, phi=phi
)
```
Do you want to give that a try and see if it produces the expected behavior?

Even so, it may be beneficial to provide a function on the Python side that automatically generates a spherical shell distribution using the code above (but that doesn't require any new infrastructure on the C++ side)

**Comment by cfichtlscherer** [comment]
Yes, I am happy to do that. But wouldn't it make more sense if we implemented a `stats.CosUniform` distribution and forward it then into `Sphericalndependent`? 
If I understand it correct, I find it a bit inconsistent if we determine the radius with the PowerLaw (power three is also needed here) but determine the angles uniform. Then one of the angels is changed again in the class?

So I would suggest adding a `stats.CosUniform` which would have a theta1 and theta2 as an input.
(0 <= theta1 <= theta2 <= pi)

`stats.CosUniform` would then determine:
> arccos((|cos(theta1) - cos(theta2)| * U(0,1)) - cos(theta1))

(I think this should work, but I will check again)

This would lead to values whose cosine is uniform distributed between theta1 and theta2.

It could then be forwarded to the `Sphericalndependent` class.

After that, I would then write a python part, which facilitates the input again?

Such that sources can be written in this simple way of 

```
source.space = openmc.stats.Spherical((radius2, r2), (phi1, phi2), (theta1, theta2),  (x, y, z)) 
```

What do you think?

**Comment by eepeterson** [comment]
@paulromano I tend to agree with @cfichtlscherer on adding a `stats` distribution something like `openmc.stats.HalfSine` or the like because it hurts my OCD to change `theta` to `cos(theta)` and break the consistency with other coordinate systems. However, I do get that there aren't many physical systems with half sine wave probability distributions, but it is relatively simple and parabola-esque and may find use by some users. You could then add an `openmc.stats.UniformSpherical` class as a wrapper so users don't need to know they have to use the `HalfSine` distribution. However, if this approach seems unappealing we can change the argument, but it would be a breaking change obviously.

**Comment by paulromano** [comment]
Yeah, I feel you @eepeterson. My OCD tells me that too :smile: and I truly don't like to make breaking changes. **But** the problem I'm having is thinking about other use cases. Let's say we had a `HalfSine` distribution that you could feed into `theta`. If the user wanted to, e.g., specify a distribution in the top half of a sphere, what would that look like? It seems to me that it would be quite awkward with this `HalfSine` distribution. The nice thing about specifying `cos_theta` for `SphericalIndependent` is that if you want uniform points in some fraction of a sphere, it makes it a lot easier to reason about how to do it (in this example, just use `Uniform(0, pi/2)`).

**Comment by paulromano** [comment]
> You could then add an `openmc.stats.UniformSpherical` class

Forgot to respond to this -- I completely agree that we should provide an abstraction on top of `SphericalIndependent` for uniform sampling, but it doesn't need to be a new class. A normal function should suffice.

**Comment by eepeterson** [comment]
@paulromano I do agree that telling `cos(theta)` to be uniform on some interval is probably simpler to understand, but I don't quite see the awkwardness you're talking about, but perhaps I'm missing something? The `openmc.stats.UniformSpherical` distribution should be able to return the user a uniformly sampled upper hemisphere if they only wanted `theta` from 0 to pi/2. It should have the capability to uniformly sample any subset of a sphere. If someone wanted to use `SphericalIndependent` to generate a uniformly sampled upper hemisphere for some reason then they would just pass `theta=HalfSine(0, pi/2)`, but the `UniformSpherical` helper takes care of that for them.

**Comment by paulromano** [comment]
The awkwardness to me is the meaning of `HalfSine(0, pi/2)`. The meaning we'd want for this application is "sin(x), but only the region in [0,pi/2]", but I could easily see this as being interpreted as "half of a sine wave, but scaled to the interval [0,pi/2]". So, that together with the fact that `HalfSine` would require a new Python and C++ class have me leaning a bit more strongly toward the `cos_theta` idea. Another point in favor of the `cos_theta` approach is the fact that sampling using the `HalfSine` approach would require 1) sampling a uniform distribution, 2) taking arccos on the result, and then 3) taking cos of that.

**Comment by eepeterson** [comment]
Ah ok I see what you're saying now and those are all good points @paulromano and I'm fine with changing to `cos_theta` if you want. I did take a look at scipy distributions and the [cosine](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.cosine.html) distribution would fulfill the same objective of the `HalfSine` distribution if you shift, scale, and truncate it. I think the only remaining question that this brings up in my mind is would we want a general capability of sampling truncated distributions and/or expanding support for other types of analytical distributions in order to save people from going down the custom source route?

**Comment by paulromano** [comment]
> would we want a general capability of sampling truncated distributions and/or expanding support for other types of analytical distributions in order to save people from going down the custom source route?

In general, I would take cues from users — if there are **common** use cases that are not appropriately handled through our existing distributions, we ought to consider how to better handle those. I don't think, however, that we should create new analytical distributions for every one-off use case. After all, that is the purpose of having a custom source facility in the first place.

@cfichtlscherer Are you comfortable with going ahead and switching `SphericalIndependent` to use `cos_theta` as part of this PR (or alternatively on a new PR)?

**Comment by cfichtlscherer** [comment]
@paulromano yes I will do it

**Comment by cfichtlscherer** [comment]
I created a new pull request for this issue

_Uniform distribution of cos(theta) in SphericalIndependent_ #2061 

@paulromano @eepeterson thanks again for the discussion :smiley:

I will close this pull request here.

**Pull request closed without merging**
