### PR TITLE
modifications to allow one sided cones to live alongside dual sided cones

### PR DESCRIPTION
**Pull request by makeclean**
Hi all, again consider this a draft. This is what im thinking about cones, this hasnt really changed a lot for a few months. These changes allow MCNP likes cones to be supported, ie you can add an additional sign term +1/-1 to inside if one wants the up or down part of the sheet cone.

### CODE REVIEW

**Comment by paulromano** [comment]
@makeclean I came up with a clever way of handling one-sided cones that is substantially simpler than actually extending the definition of cones in Python/C++. Instead, what we can do is have a "composite" surface that actually stores a cone and a plane (as an ambiguity surface) under the hood. When you ask for the positive or negative halfspace, it gives you the correct combination. So, it looks like:
```Python
class XConeOneSided:
    def __init__(self, x0, y0, z0, r2, up):
        self.cone = openmc.XCone(x0, y0, z0, r2)
        self.plane = openmc.XPlane(x0)
        self.up = up

    def __neg__(self):
        return -self.cone & (+self.plane if self.up else -self.plane)

    def __pos__(self):
        return +self.cone & (+self.plane if self.up else -self.plane)
```
Translating and rotating such a composite surface just entails translating/rotating the individual surfaces that are stored internally.

If you're agreeable on this approach, I think we can go ahead and close this PR. I'll submit a PR later implementing this once @eepeterson is done doing some refactoring/additions to surfaces.

**Comment by eepeterson** [comment]
Nice @paulromano! One thing I was thinking about (and we might have chatted about it the other day) was that this framework would be pretty helpful in an abstract MacroSurface or CompositeSurface class which could be extended to implement these types of cones, boxes, or more complicated things like arbitrary axisymmetric RZ-paths from a list of points, which I've done for my own research, but in a slightly hacky way.

**Comment by paulromano** [comment]
@eepeterson absolutely -- for converting MCNP models, I have a slew of these "composite" surfaces (macrobodies as MCNP calls them), and it's really easy to add more

**Comment by makeclean** [comment]
Go for it, thats much neater!

**Comment by paulromano** [comment]
Closing based on the above discussion

**Pull request closed without merging**
