### PR TITLE
Hotfix for heating data, and other patches

### PR DESCRIPTION
**Pull request by paulromano**
The main purpose of this PR is to fix the heating data pulled from ACE files (@liangjg noted after #1191 was merged that the wrong array was getting pulled in). There are a few other updates as well:

- Build warnings from gcc/clang are fixed.
- All our `export_to_xml` methods now work when given a directory as a path
- Include particle type in the source bank when its written to file

### CODE REVIEW

**Comment by liangjg** [comment]
@paulromano I guess you also need to update the link to the test nndc data in `tools/ci/download-xs.sh` to pass the test?

**Comment by liangjg** [comment]
@paulromano I did a `heating` tally using the new library and found the neutron heating is inconsistent with the `kappa-fission` tally in the fuel region, about 2 orders of magnitude smaller. Then I figured out that the `heating numbers`, i.e., `MT 301` in ACE, is not the `heat production cross section` in unit of "eV·barn", but are the `heating factors` in "eV per reaction", i.e. the `heat production cross section` divided by total cross section, as documented in [NJOY ACER manual](https://github.com/njoy/NJOY2016-manual/blob/master/acex.tex#L252). So to make sure the `heating` tally is getting the neutron energy deposition, we should modify either the library data or the tallying procedure by multiplying the `MT 301` data with total cross section. What do you think?

**Comment by makeclean** [comment]
That's correct, 301 needs to be multiplied by the total cross section

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by paulromano** [comment]
@liangjg Ok, I updated the data tarball, and the `from_ace` method so that it multiples the heating number by the total cross section. Hopefully this is good now.

**Pull request merged**
