### PR TITLE
Warning fixes

### PR DESCRIPTION
**Pull request by roystgnr**
These aren't particularly important changes, but after these surprisingly-few commits my personal paranoid build settings (```-Werror -Wall -Wextra``` plus more handpicked warnings) came up clean.

I chose the ```decltype``` solution in that first commit to try to make the change forwards-compatible (vs hard-coding a new index type) and minimally invasive (vs switching to a range for plus an offset variable), but it might not be the best solution.

### CODE REVIEW

**Comment by roystgnr** [comment]
> came up clean

No, I take that back; looking again through build logs I'm seeing other compiler warnings that I just hadn't looked into because they weren't related to a couple errors in a different code.  Still, this is a start.

**Comment by gridley** [comment]
Nice!

Two warnings sticking out for me like a sore thumb are the unused variables `surf1_is_xyplane` and `surf2_is_xyplane` in boundary_condition.cpp.

If you're busy working on other things now @roystgnr, I may make a PR to your fork's branch to add some more warning fixes at some point.

**Comment by roystgnr** [comment]
> If you're busy working on other things now @roystgnr

I'm afraid I am; this was an "I already fixed a couple things and don't want to be too lazy to send fixes upstream" PR, not an "I am going to crusade to completely fix all instances of this issue" PR.  Think of these commits as suggestions; please feel free to expand upon or edit them to better fit your style.

**Review by paulromano — APPROVED** [review]
Thanks for the warning fixes @roystgnr! I appreciate you taking the time to put in the PR, even if it is small. @gridley If you have more, feel free to submit a separate PR.

**Pull request merged**
