### PR TITLE
Fixed typo from last pull request

### PR DESCRIPTION
**Pull request by mkreher13**
Very sorry for missing this in my last PR. Since there isn't a test for create_mg_mode with
these delayed mgxs types, it's not super easy to catch such errors.

### CODE REVIEW

**Comment by mkreher13** [comment]
I'm running into some issues in the source code. I believe the same functions that make exceptions for the presence of 'beta' in the mgxs_types are required for 'decay-rate'. I am still working on resolving this.

**Comment by mkreher13** [comment]
@nelsonag If you have the time, let me know what you think of this change. Without it, the python-side and the c-side requested incompatible shapes for the decay-rate vector.

**Comment by nelsonag** [comment]
@mkreher13 sure, i hope to get to it tomorrow. Sorry been quite busy recently! Did your last few commits address the issue you noted 2 comments ago?

**Comment by mkreher13** [comment]
No worries, It's not time-sensitive. 

Yes, all fixed. Runs smoothly on my end when I create a mgxs_library that includes decay-rate, use create_mg_mode, and then run in mg-mode. I'm open to criticism if you see a different way of fixing the issue.

**Review by nelsonag — APPROVED** [review]
Looks good to me! Thanks @mkreher13!

**Pull request merged**
