### PR TITLE
moving from dagmc develop to latest tagged release

### PR DESCRIPTION
**Pull request by Shimwell**
Perhaps overdue minor changed to the Dockerfile that tags a specific version of DAGMC.

Occasionally the develop branch [fails](https://app.circleci.com/pipelines/github/svalinn/DAGMC) to build, tagging the latest release is probably advisable

If people like tagged then this PR can be expanded to include tagged versions for other codes such as Embree MOAB

### CODE REVIEW

**Comment by pshriwise** [comment]
Thanks for this @Shimwell! It looks like we should go ahead and do the same with CI as well...

**Comment by pshriwise** [comment]
And to answer your question about the other versions. Yeah, I think fixing those as well would be a good idea.

**Comment by Shimwell** [comment]
I can update the CI scripts if that helps
Perhaps this can change to  MOAB_BRANCH='5.2.1' https://github.com/openmc-dev/openmc/blob/aeee1664f363495106c322317dc319bf45412045/tools/ci/gha-install-dagmc.sh#L6

and this could be changed to DAGMC_BRANCH='3.2.0' https://github.com/openmc-dev/openmc/blob/aeee1664f363495106c322317dc319bf45412045/tools/ci/gha-install-dagmc.sh#L11

It looks like Embree is not used in the CI installation scripts

Just to throw this out there as an option, the dockerfile could also be reshaped to allow build arguments and then cover all CI environments but perhaps that is too much change at the moment.

**Comment by pshriwise** [comment]
I like the option of adding optional build args for the Dockerfile in the future. If you'd like to give it a try, go for it!

For CI, we're going to discuss the pros and cons of fixing these optional dependency versions in CI soon, so let's hold off on that for now.

**Review by pshriwise — APPROVED** [review]
Thanks @Shimwell! It will be nice to have stable versions in the Dockerfile. They can always be updated to development versions by those using the file if needed.

**Pull request merged**
