### PR TITLE
Add dose coefficients from ICRP 74

### PR DESCRIPTION
**Pull request by MatteoZammataro**
This PR is related to issue #2516, and it's an extension of PR #2749. It adds H*(10) dose coefficients from ICRP 74.
We're introducing a new function, "dose_coefficients()." 

This function has a "data_source" argument, which you can set to icrp74, icrp116, or icrp119 (the default is icrp116). 
This allows for using both effective and ambient dose coefficients. When you use the effective dose ones, the syntax is basically the same as before. 

Any suggestions for improvement are welcome.

I would like to extend my gratitude to @shimwell for his contributions to this topic thus far.

### CODE REVIEW

**Comment by MatteoZammataro** [comment]
@paulromano If you are not available, could you please suggest another independent reviewer?

**Comment by paulromano** [comment]
@MatteoZammataro sorry I haven't had a chance to look at this yet. As you've probably figured, I'm working to get through the backlog of PRs and will take a look at this shortly.

**Review by paulromano — CHANGES_REQUESTED** [review]
@MatteoZammataro thanks for this PR! I made some updates on your branch and, notably, removed the ICRP 119 data for now (see my comments on #2749).

One change that's needed is that the ICRP 74 neutron data should be from Table A.41 rather than A.42. Can you make that update?

**Review by paulromano — APPROVED** [review]
@MatteoZammataro Thanks for the updates! I made a few more changes here, including adding a script that will generate the photon effective dose per fluence values so that the origin of the data is a little more traceable. I agree with your approach of multiply the Table A.1 and A.17 values. Interestingly, looking through the literature, when people say "we used ICRP74 to compute photon dose", it gets interpreted in many different ways (some use air kerma from table A.1, some use Table A.21 ambient dose equivalent, and some use A.1×A.17).

**Pull request merged**
