### PR TITLE
adding resulting nuclide to cross section plot legend

### PR DESCRIPTION
**Pull request by shimwell**
This PR attempts to add the resulting nuclide to the legend in the cross section plot.

I have tried to make use of existing code by recycling the ```dadz``` values originally from chain.py and placing them in data.py. I guess they might be useful elsewhere as well

On the left we have the resulting plot currently and on the right we have the plot after this PR

Screenshot from 2024-01-19 17-47-01

*edited plot updated to fix bug spotted by @makeclean 

# Checklist

- [x] I have performed a self-review of my own code
- [x] I have followed the [style guidelines](https://docs.openmc.org/en/latest/devguide/styleguide.html#python) for Python source files (if applicable)

### CODE REVIEW

**Comment by makeclean** [comment]
Something isn't right there -
Ta181(n,a) can't go upto Re185, it should be Re177 right? when you loose an alpha you lose 4 nucleons

On Fri, 2024-01-19 at 08:59 -0800, Jonathan Shimwell wrote:
This PR attempts to add the resulting nuclide to the legend in the cross section plot.
On the left we have the resulting plot currently and on the right we have the plot after this PR
Screenshot.from.2024-01-19.16-51-39.png (view on web)
Checklist * I have performed a self-review of my own code
 * I have followed the style guidelines for Python source files (if applicable)
You can view, comment on, or merge this pull request online at:  https://github.com/openmc-dev/openmc/pull/2851
Commit Summary * 6a21741 adding resulting nuclide to legend
 * b3c07ac using existing import
File Changes (3 files)
 * M openmc/data/data.py (87)
 * M openmc/deplete/chain.py (169)
 * M openmc/plotter.py (5)
Patch Links: * https://github.com/openmc-dev/openmc/pull/2851.patch
 * https://github.com/openmc-dev/openmc/pull/2851.diff

**Comment by shimwell** [comment]
Thanks @makeclean for spotting that I have updated the plot and code.

**Review by paulromano — APPROVED** [review]
Thanks @shimwell! FYI I made a change here removing the `dadz` from `ReactionInfo` rather than storing it redundantly. It was straightforward to just use the `DADZ` directly in the code below in chaing.py.

**Comment by shimwell** [comment]
Many thanks Paul that is certainly more elegant

**Pull request merged**
