### PR TITLE
Adds MPACT library group structures and documentation to mgxs collection

### PR DESCRIPTION
**Pull request by bscollin**
# Description

Group structures from the MPACT reactor physics code are added to the `mgxs.GROUP_STRUCTURES` python dictionary.  These include a 51g structure used primarily for PWRs, a 60g structure developed for BWRs, a 69g structure developed for Magnox reactors, and a 252g structure that should be good for most thermal systems.

Fixes # N/A

# Checklist

- [x] I have performed a self-review of my own code
- [x] I have followed the [style guidelines](https://docs.openmc.org/en/latest/devguide/styleguide.html#python) for Python source files (if applicable)
- [x] I have made corresponding changes to the documentation (if applicable)

### CODE REVIEW

**Review by paulromano — COMMENTED** [review]
Thanks for this contribution @bscollin! I looked at the reference provided in the comment but I only see the definition for the 51 group structure there. Where can one find the definition for the other structures?

**Comment by bscollin** [comment]
@paulromano, I pulled the data straight from the cross-section library files distributed with VERA.  I talked with Aaron Graham @aarograh, the VERA project lead at ORNL and he was okay with releasing these.  I did find a reference to the 69g Magnox library: https://www.epj-conferences.org/articles/epjconf/pdf/2021/01/epjconf_physor2020_10016.pdf
and the 252g is the same as scale:
https://serpent.vtt.fi/mediawiki/index.php/SCALE_252-group_structure
It doesn't look like they have published the BWR library structure anywhere.  I can back that one out if you would like me to.  I can also add the extra references, I just didn't want to flood the references with MPACT ones.

**Comment by paulromano** [comment]
Thanks @bscollin. Could you put those references in the docstring below `GROUP_STRUCTURES`? Also, should we refer to the 252 group structure as "SCALE-252" instead of "MPACT-252"?

**Comment by bscollin** [comment]
@paulromano All requests addressed.  Added references to 69g library, renamed 252g library to SCALE-252 and added reference.

**Review by paulromano — APPROVED** [review]
Thanks @bscollin!

**Pull request merged**
