### PR TITLE
Update CODEOWNERS file

### PR DESCRIPTION
**Pull request by paulromano**
# Description

A few updates in our CODEOWNERS file:
- For depletion, replaced @drewejohnson with @paulromano (happy to keep you there @drewejohnson but figured we should stop bugging you!)
- @pshriwise for weight windows
- @jtramm for random ray
- @marquezj for NCrystal interface
- @ebknudsen for MCPL interface

For those of you I've just tagged, please let me know if you object to being the "owner". It just means that you'll get pinged for a review if someone changes one of the associated files.

# Checklist

- [x] I have performed a self-review of my own code
- [x] <s>I have run [clang-format](https://docs.openmc.org/en/latest/devguide/styleguide.html#automatic-formatting) (version 15) on any C++ source files (if applicable)</s>
- [x] <s>I have followed the [style guidelines](https://docs.openmc.org/en/latest/devguide/styleguide.html#python) for Python source files (if applicable)</s>
- [x] <s>I have made corresponding changes to the documentation (if applicable)</s>
- [x] <s>I have added tests that prove my fix is effective or that my feature works (if applicable)</s>

### CODE REVIEW

**Review by pshriwise — CHANGES_REQUESTED** [review]
Looks like we need to provide additional permissions to @marquezj to be a codeowner:

image


Otherwise this looks good to me! Thanks for updating this 💯

**Comment by paulromano** [comment]
I invited @marquezj to the committers team so just waiting on him to accept :smile:

**Comment by marquezj** [comment]
> I invited @marquezj to the committers team so just waiting on him to accept 😄

Great! Yes, I accept. 

Should I do something on my side?

**Comment by paulromano** [comment]
@marquezj Nope! You've done everything you need to do. Thanks for accepting!

**Comment by ebknudsen** [comment]
Just to be clear - I gladly accept my task as well.

**Comment by drewejohnson** [comment]
I don't mind the nagging, just so long as you all don't mind me being very slow to respond :sweat_smile: I'm not on GitHub that much, but I still want to support this project as I can

**Review by pshriwise — APPROVED** [review]
Thanks @paulromano!

**Pull request merged**
