### PR TITLE
added paper by @jbae11 and @eepeterson

### PR DESCRIPTION
**Pull request by shimwell**
Just adding a recent paper to the list of publications in the docs.

@jbae11 and @eepeterson

### CODE REVIEW

**Comment by paulromano** [comment]
@shimwell I gave up on trying to add all relevant publications in our main documentation because there are just so many of them these days. I've switched over to just posting on the [Papers](https://openmc.discourse.group/t/papers-using-openmc/787/60) topic on discourse.

**Comment by shimwell** [comment]
Ah sorry, I didn't realize there was a discourse list of paper

I guess there is a risk that others also see this list of publications on the readthedocs site and  also think this is the full list.

**Comment by paulromano** [comment]
Yeah, if anything we might want to trim down this list to just the "main" OpenMC papers

**Comment by shimwell** [comment]
It is quite nice to have papers broken down by subject like you currently have on readthedocs 👍 .

I see the publication rate has just grown 📈 to such an extent that maintaining the list is difficult.

Perhaps we can leave the readthedocs as it is but just add link 🔗 to the larger list on the discourse channel ?

**Comment by shimwell** [comment]
I think it is best to close this PR. Thanks for updating me on the publication list Paul. Sorry for taking up your time.

**Pull request closed without merging**
