### PR TITLE
purxs-openmc merge

### PR DESCRIPTION
**Pull request by walshjon**
This PR constitutes the illegitimate lovechild of my URR package, purxs, and openmc.  Please be kind to her --- she's a little slow.

purxs is configured as a submodule of openmc.  In the repo, currently inaccessible to most, I provide:
-- necessary data (evaluations for a few isotopes, average xs computed with purxs)
-- doxygen documentation (run doxygen in /purxs/docs/man to build)
-- example inputs for key functionality
-- python module for building urr.xml inputs
-- scripts that used the python to build inputs  (self-explanatory to use)
-- src
-- a simple testing framework (out-of-date)

@bforget @paulromano

### CODE REVIEW

**Comment by cjosey** [comment]
I am in no way technically qualified to review this, but I thought I'd make a few mentions of possible issues to get you a headstart on the oncoming storm.  Last night I was just going to post "Oh boy here we go." but this is more productive.

- I can't really tell without access to the ``purxs`` repo, but why are there two ``Faddeeva.c`` files?  Also, later on I see a switch between Faddeeva versions.  I would suggest picking just one unless there is a real critical performance/accuracy reason.
- The Fox XML library has been completely removed.  I would suggest removing that from ``.gitmodules``.
- Line 38, ``src/finalize.F90`` has an ``#ifdef HDF5``.  In current OpenMC, this will always evaluate to true.
- There are a lot of random changes, mostly in formatting.  But weird ones like lines 157 and 158 in ``plot.F90``.  It seems like in bringing it up to the newest version, a lot of newer changes might've been reverted.  I'd try to minimize the line change count just by eliminating all changes that have nothing to do with your work, and then possibly doing ``git rebase`` to reduce the complexity of the PR.
- ``read_tallies_xml`` in ``input_xml.F90`` has a bunch of commented out code.
- I think we've tried to eliminate ``threadprivate`` as much as possible.

Other miscellaneous comments.
- I have never heard of MNBW the cross section format.  Is this just MLBW but actually applied to all reactions instead of the ENDF-6 discount MLBW format?

**Comment by walshjon** [comment]
Thanks @cjosey .  Here are some responses:

I can't really tell without access to the purxs repo, but why are there two Faddeeva.c files? Also, later on I see a switch between Faddeeva versions. I would suggest picking just one unless there is a real critical performance/accuracy reason.

**I set up purxs to be a standalone package, so it needs its own faddeeva evaluation.  Depending on how we want to handle the purxs submodule (e.g., do we just want to take the current code and integrate it tightly with OpenMC, or allow for pulling in the current purxs develop), this could be stripped out (in the openmc submodule purxs code).**

    The Fox XML library has been completely removed. I would suggest removing that from .gitmodules.

**Agreed.  I'm not using FoX.**

    Line 38, src/finalize.F90 has an #ifdef HDF5. In current OpenMC, this will always evaluate to true.

**This was a product of the merge, I guess -- not necessary.**

    There are a lot of random changes, mostly in formatting. But weird ones like lines 157 and 158 in plot.F90. It seems like in bringing it up to the newest version, a lot of newer changes might've been reverted. I'd try to minimize the line change count just by eliminating all changes that have nothing to do with your work, and then possibly doing git rebase to reduce the complexity of the PR.

**Latest commit fixes some random stuff that happened in the merge.**

    read_tallies_xml in input_xml.F90 has a bunch of commented out code.
    I think we've tried to eliminate threadprivate as much as possible.

**I don't show much commented out code.  There's one small block, but I don't think I introduced it.**

Other miscellaneous comments.

    I have never heard of MNBW the cross section format. Is this just MLBW but actually applied to all reactions instead of the ENDF-6 discount MLBW format?

**It's the multi-niveau Breit-Wigner formalism.  It is actually mathematically different than the typical MLBW applied to all reactions.**

**Comment by paulromano** [comment]
Ok, finally getting around to taking a look at this. Thanks @cjosey for already giving some comments -- I agree with the points you made thus far. @walshjon, although I'm familiar with your work, for the benefit of others (and for posterity), you should describe in a bit of detail what the change is that you're introducing, how it works, and what the user-facing changes are. Before I get too deep into a real review, I think there are some high level philosophical questions we need to answer first:
- Are you planning on open sourcing that purxs repository?
- Are you planning on using/supporting purxs?
- Do you feel the capability introduced here is of sufficient interest to a general user? i.e., does it really belong in the develop branch of OpenMC?

And a few high-level comments:
- I don't see any documentation. At the very least, you will need to add:
  - documentation on how a user is supposed to use the feature
  - documentation on the format of the `urr.xml` file
- Nothing here seems to be usable from the Python API.
- There are no tests added.

**Comment by walshjon** [comment]
Thanks for the feedback @paulromano .  My responses are inline below.

Ok, finally getting around to taking a look at this. Thanks @cjosey for already giving some comments -- I agree with the points you made thus far. @walshjon, although I'm familiar with your work, for the benefit of others (and for posterity), you should describe in a bit of detail what the change is that you're introducing, how it works, and what the user-facing changes are. 

**I'm waiting to get purxs open-sourced before laying out all the dirty details of the capabilities it adds, and how to use it.**

Before I get too deep into a real review, I think there are some high level philosophical questions we need to answer first:
- Are you planning on open sourcing that purxs repository?

**Yes, that's the plan, and I'm in the process.**

- Are you planning on using/supporting purxs?

**There are at least a few more projects I'll be using it for, and I'd likely be able to support anyone interested in using it.**

- Do you feel the capability introduced here is of sufficient interest to a general user? i.e., does it really belong in the develop branch of OpenMC?

**There are several capabilities being introduced -- some will be of more interest than others.  @bforget has mentioned a desire to use the probability table generation/sampling capability as well as the independent realization capability for UQ.  I could envision most of the capabilities being useful to anyone performing URR evaluations.  It's a judgement call whether or not these are sufficient reasons to include it in develop.  What I don't want to do, though, is maintain a separate branch, continually merging in develop.  I think you'll find the actual changes to OpenMC source to be minimally invasive.**

And a few high-level comments:
- I don't see any documentation. At the very least, you will need to add:
  - documentation on how a user is supposed to use the feature
  - documentation on the format of the `urr.xml` file

**There's documentation in the purxs repo.  I can add more info on the openmc side once we reach answers on the above questions.  In the meantime, the examples input files will run out of the box.  The format of `urr.xml` is completely defined by the docstrings in the purxs python module for constructing inputs.  I can add something more later on.**

- Nothing here seems to be usable from the Python API.

 **I made no attempt to hook things up with the existing openmc-side python.  The purxs repo has some scripts that use the purxs python module to generate `urr.xml` inputs.  That's as far as I went.**

- There are no tests added.

**If we want to go forward with the merge, I'll add some.**

**Comment by walshjon** [comment]
Went ahead and pushed the big red button.  The [purxs](https://github.com/walshjon/purxs) repo needed for this PR is now open.

**Comment by smharper** [comment]
@walshjon, what's the status of this?  The purxs repo you linked gives me a 404.

**Comment by paulromano** [comment]
This PR has been open for two years now with no imminent sign of progress, and it is very far out of sync with the develop branch. I'm going to close the PR at this point. @walshjon If you still intend to get this in as a main feature of OpenMC, let us know and we can discuss what the right path forward is.

**Pull request closed without merging**
