### PR TITLE
Reset n_event in event_death

### PR DESCRIPTION
**Pull request by gridley**
Solves #1760

### CODE REVIEW

**Comment by jtramm** [comment]
Great find!

Is there any advantage to moving the `n_event_` reset to the `initialize_history()` function? From my read, it doesn't seem like it would make any difference, but was just curious if you had considered that.

**Comment by gridley** [comment]
Hey @jtramm, thanks. I think you're right it may go better there. Someone may at some point in the future expect to check `n_event_` after a particle death. So, fixed that.

BTW, I seem to have accidentally opened up a new branch within this repository, not my own, as a result of using the online editor since this change was so small. So we need to be sure to delete it after merging  this...

**Comment by jtramm** [comment]
Ah, yes, that's a good point. I could see someone perhaps wanting to make a histogram of # of events per history or something, so retaining that value after death could be useful.

**Review by jtramm — APPROVED** [review]
Looks good to me -- thanks @gridley!

**Pull request merged**
